<?php
/**
 * About With Counter 2
 *
 * @package CiyaShop
 */

return array(
	'name'              => esc_html__( 'About with Counter 2', 'ciyashop' ),
	'template_category' => esc_html__( 'About', 'ciyashop' ),
	'disabled'          => true, // Disable it to not show in the default tab.
	'content'           => '<<<CONTENT
<p>[vc_row full_width="stretch_row" pgscore_enable_responsive_settings="true" el_id="1521015723456-d3221c97-f654" css=".vc_custom_1521202670894{padding-top: 80px !important;padding-bottom: 50px !important;background-image: url(http://ciyashop.potenzaglobalsolutions.com/perfume/wp-content/uploads/sites/7/2018/03/about-bg.jpg?id=655) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}" element_css_md=".vc_custom_1521202670896{padding-top: 60px !important;padding-bottom: 30px !important;}" element_css_sm=".vc_custom_1521202670897{padding-top: 50px !important;padding-bottom: 20px !important;}" element_css_xs=".vc_custom_1521202670898{padding-top: 40px !important;padding-bottom: 10px !important;}"][vc_column width="5/6" offset="vc_col-lg-8 vc_col-md-9" css=".vc_custom_1521202450117{padding-top: 0px !important;}" el_id="1545125837382-54d045ed-1f84"][vc_custom_heading text="Get to know us better" font_container="tag:h3|text_align:left" use_theme_fonts="yes" font_weight="600" css=".vc_custom_1521027372630{margin-bottom: 30px !important;}"][vc_column_text]</p>
<blockquote><p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident.</p></blockquote>
<p>[/vc_column_text][vc_column_text]Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae.[/vc_column_text][vc_row_inner][vc_column_inner width="1/4" css=".vc_custom_1521021715371{margin-bottom: 30px !important;}"][pgscore_counter counter_alighnment="left" counter_title_font_size="16" counter_number="227" counter_number_font_size="40" counter_icon_size="xs" counter_icon_color="#e32a53" icon_fontawesome="fa fa-pencil" counter_title="Designer Brands"][/vc_column_inner][vc_column_inner width="1/4" css=".vc_custom_1521021721090{margin-bottom: 30px !important;}"][pgscore_counter counter_alighnment="left" counter_title_font_size="16" counter_number="2463" counter_number_font_size="40" counter_icon_size="xs" counter_icon_color="#e32a53" icon_fontawesome="fa fa-smile-o" counter_title="Happy Clients"][/vc_column_inner][vc_column_inner width="1/4" css=".vc_custom_1521021725572{margin-bottom: 30px !important;}"][pgscore_counter counter_alighnment="left" counter_title_font_size="16" counter_number="29" counter_number_font_size="40" counter_icon_size="xs" counter_icon_color="#e32a53" icon_type="linecons" icon_linecons="vc_li vc_li-shop" counter_title="Cosmetic Stores"][/vc_column_inner][vc_column_inner width="1/4" css=".vc_custom_1521021731298{margin-bottom: 30px !important;}"][pgscore_counter counter_alighnment="left" counter_title_font_size="16" counter_number="795" counter_number_font_size="40" counter_icon_size="xs" counter_icon_color="#e32a53" icon_fontawesome="fa fa-gift" counter_title="Gift Cards Issued"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]</p>
CONTENT',
);
