<?php
/**
 * About With Info Box 2
 *
 * @package CiyaShop
 */

return array(
	'name'              => esc_html__( 'About With Info Box 2', 'ciyashop' ),
	'template_category' => esc_html__( 'About', 'ciyashop' ),
	'disabled'          => true, // Disable it to not show in the default tab.
	'content'           => <<<CONTENT
[vc_row full_width="stretch_row" equal_height="yes" content_placement="middle" pgscore_enable_responsive_settings="true" el_id="1533298091712-0962df14-f3e0" css=".vc_custom_1545639487851{padding-top: 60px !important;padding-bottom: 90px !important;background-color: #fbf7f6 !important;}" element_css_md=".vc_custom_1545639487852{padding-top: 20px !important;padding-bottom: 60px !important;}" element_css_sm=".vc_custom_1545639487853{padding-top: 10px !important;padding-bottom: 50px !important;}" element_css_xs=".vc_custom_1545639487855{padding-top: 0px !important;padding-bottom: 40px !important;}"][vc_column offset="vc_col-lg-6 vc_col-md-6" el_id="1545116098280-b2316232-3600"][vc_custom_heading text="Why Choose Us?" use_theme_fonts="yes"][vc_column_text css=".vc_custom_1533644905076{margin-top: 10px !important;margin-bottom: 30px !important;}"]I truly believe Augustine's words are true and if you look at history you know it is true. There are many people in the world with amazing talents who realize only a small percentage of their potential.[/vc_column_text][pgscore_info_box_2 icon_position="left" title_el="h4" description_color="#888888" icon_size="lg" icon_source="link" layout="style_2" title="100% Pure Leather" icon_image="488" content_alignment="center" add_anchor="" anchor_link="" title_color="#323232" info_content="Commitment – understanding the price<br />
and having the willingness to pay that price" background_options="border" title_hover_color="#04d39f" backround_img="" element_back_color="#F5F5F5" element_hover_color="#323232" border_width="5" border_color="#F5F5F5" border_hover_color="#04d39f" icon_style="default" add_animation="true" icon_shape="square" icon_background_color="#cccccc" icon_border_color="#cccccc" icon_color="#323232" element_css="" element_id="" element_class="" icon_type="fontawesome" icon_fontawesome="fa fa-info-circle" icon_openiconic="vc-oi vc-oi-dial" icon_typicons="typcn typcn-adjust-brightness" icon_entypo="entypo-icon entypo-icon-note" icon_linecons="vc_li vc_li-heart" icon_monosocial="vc-mono vc-mono-fivehundredpx" icon_material="vc-material vc-material-cake" icon_pixelicons="vc_pixel_icon vc_pixel_icon-alert" icon_flaticon="" disable_animation="" image_link="https://ciyashop.potenzaglobalsolutions.com/leather/wp-content/uploads/sites/28/2018/08/icon-01.png" icon_themefy="ti-arrow-up"][vc_empty_space height="40px"][pgscore_info_box_2 icon_position="left" title_el="h4" description_color="#888888" icon_size="lg" icon_source="link" layout="style_2" title="Free Delivery" icon_image="489" content_alignment="center" add_anchor="" anchor_link="" title_color="#323232" info_content="Printin k a of type and lorem Ipsum<br />
is simply dummy text of the galley" background_options="border" title_hover_color="#04d39f" backround_img="" element_back_color="#F5F5F5" element_hover_color="#323232" border_width="5" border_color="#F5F5F5" border_hover_color="#04d39f" icon_style="default" add_animation="true" icon_shape="square" icon_background_color="#cccccc" icon_border_color="#cccccc" icon_color="#323232" element_css="" element_id="" element_class="" icon_type="fontawesome" icon_fontawesome="fa fa-info-circle" icon_openiconic="vc-oi vc-oi-dial" icon_typicons="typcn typcn-adjust-brightness" icon_entypo="entypo-icon entypo-icon-note" icon_linecons="vc_li vc_li-heart" icon_monosocial="vc-mono vc-mono-fivehundredpx" icon_material="vc-material vc-material-cake" icon_pixelicons="vc_pixel_icon vc_pixel_icon-alert" icon_flaticon="" disable_animation="" image_link="https://ciyashop.potenzaglobalsolutions.com/leather/wp-content/uploads/sites/28/2018/08/icon-02.png" icon_themefy="ti-arrow-up"][vc_empty_space height="40px"][pgscore_info_box_2 icon_position="left" title_el="h4" description_color="#888888" icon_size="lg" icon_source="link" layout="style_2" title="High Quality Product" icon_image="490" content_alignment="center" add_anchor="" anchor_link="" title_color="#323232" info_content="Text of the printin lorem ipsum the<br />
is simply k a type text and galley of" background_options="border" title_hover_color="#04d39f" backround_img="" element_back_color="#F5F5F5" element_hover_color="#323232" border_width="5" border_color="#F5F5F5" border_hover_color="#04d39f" icon_style="default" add_animation="true" icon_shape="square" icon_background_color="#cccccc" icon_border_color="#cccccc" icon_color="#323232" element_css="" element_id="" element_class="" icon_type="fontawesome" icon_fontawesome="fa fa-info-circle" icon_openiconic="vc-oi vc-oi-dial" icon_typicons="typcn typcn-adjust-brightness" icon_entypo="entypo-icon entypo-icon-note" icon_linecons="vc_li vc_li-heart" icon_monosocial="vc-mono vc-mono-fivehundredpx" icon_material="vc-material vc-material-cake" icon_pixelicons="vc_pixel_icon vc_pixel_icon-alert" icon_flaticon="" disable_animation="" image_link="https://ciyashop.potenzaglobalsolutions.com/leather/wp-content/uploads/sites/28/2018/08/icon-03.png" icon_themefy="ti-arrow-up"][/vc_column][vc_column offset="vc_col-lg-6 vc_col-md-6" el_id="1545116098339-9a64f94a-a264"][vc_single_image source="external_link" alignment="center" custom_src="http://ciyashop.potenzaglobalsolutions.com/leather/wp-content/uploads/sites/28/2018/08/why-choose.png"][/vc_column][/vc_row]
CONTENT
);
