<?php
/**
 * About Box Image Color Overlay
 *
 * @package CiyaShop
 */

return array(
	'name'              => esc_html__( 'Action Box Bg Image', 'ciyashop' ),
	'template_category' => esc_html__( 'Action Box', 'ciyashop' ),
	'disabled'          => true, // Disable it to not show in the default tab.
	'content'           => '<<<CONTENT
[vc_row full_width="stretch_row" pgscore_bg_type="row-background-dark" pgscore_background_position="center-center" enable_first_overlay="true" first_overlay_opacity="40" first_background_color="#000000" enable_parallax="true" parallax_background="11040" parallax_style="classic-fast" pgscore_enable_responsive_settings="true" pgscore_enable_overlay="true" el_id="1519389276648-af4df3b3-9647" css=".vc_custom_1543927322615{padding-top: 100px !important;padding-bottom: 100px !important;background-image: url(https://ciyashop.potenzaglobalsolutions.com/denim/wp-content/uploads/sites/32/2018/08/slide-01-1.jpg?id=14) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}" element_css_md=".vc_custom_1543927322616{padding-top: 80px !important;padding-bottom: 80px !important;}" element_css_sm=".vc_custom_1543927322618{padding-top: 60px !important;padding-bottom: 60px !important;}" element_css_xs=".vc_custom_1543927322619{padding-top: 40px !important;padding-bottom: 40px !important;}" pgscore_overlay_color="rgba(0,0,0,0.4)" el_class="action-box"][vc_column css=".vc_custom_1519390106353{padding-top: 0px !important;}"][vc_row_inner css=".vc_custom_1519389915142{padding-right: 15px !important;padding-left: 15px !important;}"][vc_column_inner pgscore_enable_responsive_settings="true" css=".vc_custom_1543637627274{border-top-width: 4px !important;border-right-width: 4px !important;border-bottom-width: 4px !important;border-left-width: 4px !important;padding-top: 40px !important;padding-right: 10% !important;padding-bottom: 40px !important;padding-left: 10% !important;border-left-color: #ffffff !important;border-left-style: solid !important;border-right-color: #ffffff !important;border-right-style: solid !important;border-top-color: #ffffff !important;border-top-style: solid !important;border-bottom-color: #ffffff !important;border-bottom-style: solid !important;}" element_css_sm=".vc_custom_1543637627278{padding-top: 30px !important;padding-right: 7% !important;padding-bottom: 30px !important;padding-left: 7% !important;}" element_css_xs=".vc_custom_1543637627279{padding-top: 20px !important;padding-right: 5% !important;padding-bottom: 20px !important;padding-left: 5% !important;}"][vc_custom_heading text="WE OFFER FASHION ACCESSORIES AT 50% DISCOUNT" font_container="tag:h2|text_align:center" use_theme_fonts="yes" font_weight="600"][vc_custom_heading text="We sell not only top quality products, but give our customers a positive online shopping experience. Purchase the goods you need every day or just like in a few clicks or taps, depending on the device you use to access the Internet." font_container="tag:p|text_align:center" use_theme_fonts="yes" font_weight="400"][vc_btn title="SHOP NOW" style="flat" shape="square" color="white" align="center" link="url:%23|||" css=".vc_custom_1534394502057{margin-bottom: 0px !important;}"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]
CONTENT',
);
