<?php
/**
 * Category 3 Images style
 *
 * @package CiyaShop
 */

return array(
	'name'              => esc_html__( 'Category 3 Images style', 'ciyashop' ),
	'template_category' => esc_html__( 'Category', 'ciyashop' ),
	'disabled'          => true, // Disable it to not show in the default tab.
	'content'           => '<<<CONTENT
[vc_row equal_height="yes" content_placement="middle" pgscore_enable_responsive_settings="true" el_id="1532945768785-fbbc5e36-b2b2" css=".vc_custom_1533095857716{padding-top: 100px !important;padding-bottom: 60px !important;}" element_css_md=".vc_custom_1533095857718{padding-top: 80px !important;padding-bottom: 50px !important;}" element_css_sm=".vc_custom_1533095857719{padding-top: 70px !important;padding-bottom: 40px !important;}" element_css_xs=".vc_custom_1533095857721{padding-top: 60px !important;padding-bottom: 30px !important;}"][vc_column alignment="right" css=".vc_custom_1542957748365{margin-bottom: 30px !important;}" offset="vc_col-lg-3 vc_col-md-12"][vc_custom_heading text="End of Season" font_container="tag:h2|font_size:4rem|text_align:right|line_height:1.2em" use_theme_fonts="yes" el_class="text-sm-right"][vc_column_text el_class="text-sm-right" css=".vc_custom_1533274553532{margin-bottom: 10px !important;}"]
<p style="text-align: right">Avail massive discounts and get exciting offers with our shopping across all new arrival categories</p>
[/vc_column_text][vc_empty_space height="1" css=".vc_custom_1542959313453{margin-top: 20px !important;margin-left: 80% !important;border-top-width: 1px !important;border-right-width: 1px !important;border-bottom-width: 1px !important;border-left-width: 1px !important;border-left-color: #323232 !important;border-left-style: solid !important;border-right-color: #323232 !important;border-right-style: solid !important;border-top-color: #323232 !important;border-top-style: solid !important;border-bottom-color: #323232 !important;border-bottom-style: solid !important;}"][pgscore_button button_background_color="#323232" button_background_hover_color="#04d39f" button_link="url:%23|title:Shop%20Now||" element_css=".vc_custom_1543407764074{margin-top: 20px !important;}"][/vc_column][vc_column width="1/2" css=".vc_custom_1533045292174{margin-bottom: 70px !important;}" offset="vc_col-lg-3 vc_col-md-4"][vc_single_image source="external_link" custom_src="http://ciyashop.potenzaglobalsolutions.com/wp-content/uploads/2018/07/season-img1.jpg"][vc_row_inner equal_height="yes" content_placement="middle" css=".vc_custom_1532957025704{margin-top: -70px !important;margin-right: 0px !important;margin-left: 0px !important;}"][vc_column_inner width="1/4" offset="vc_col-xs-2"][vc_empty_space height="2" css=".vc_custom_1542960139880{margin-top: -18px !important;background-color: #ffffff !important;}"][/vc_column_inner][vc_column_inner width="3/4" offset="vc_col-xs-10" css=".vc_custom_1532949513241{margin-left: -14px !important;}"][vc_column_text]<a style="font-size: 24px;color: #fff" href="https://ciyashop.potenzaglobalsolutions.com/shop/?product_cat=woman">Women’s</a>[/vc_column_text][/vc_column_inner][/vc_row_inner][/vc_column][vc_column width="1/2" css=".vc_custom_1533045445940{margin-bottom: 70px !important;}" offset="vc_col-lg-3 vc_col-md-4"][vc_single_image source="external_link" custom_src="http://ciyashop.potenzaglobalsolutions.com/wp-content/uploads/2018/07/season-img2.jpg"][vc_row_inner equal_height="yes" content_placement="middle" css=".vc_custom_1532957038609{margin-top: -70px !important;margin-right: 0px !important;margin-left: 0px !important;}"][vc_column_inner width="1/4" offset="vc_col-xs-2"][vc_empty_space height="2" css=".vc_custom_1542960156632{margin-top: -18px !important;background-color: #323232 !important;}"][/vc_column_inner][vc_column_inner width="3/4" offset="vc_col-xs-10" css=".vc_custom_1532949513241{margin-left: -14px !important;}"][vc_column_text]<a style="font-size: 24px;color: #323232" href="https://ciyashop.potenzaglobalsolutions.com/shop/?product_cat=kids">Kids</a>[/vc_column_text][/vc_column_inner][/vc_row_inner][/vc_column][vc_column css=".vc_custom_1533045320163{margin-bottom: 30px !important;}" offset="vc_col-lg-3 vc_col-md-4"][rev_slider_vc alias="banner-video"][/vc_column][/vc_row]

CONTENT',
);
