<?php
/**
 * Contact Info 3 Box
 *
 * @package CiyaShop
 */

return array(
	'name'              => esc_html__( 'Contact Info 3 Box', 'ciyashop' ),
	'template_category' => esc_html__( 'Contact Info', 'ciyashop' ),
	'disabled'          => true, // Disable it to not show in the default tab.
	'content'           => '<<<CONTENT
[vc_row pgscore_enable_responsive_settings="true" el_id="1517578456227-29bbaeb3-545d" css=".vc_custom_1517817973842{margin-top: 80px !important;margin-bottom: 50px !important;}" element_css_md=".vc_custom_1517817973844{margin-top: 60px !important;margin-bottom: 30px !important;}" element_css_sm=".vc_custom_1517817973846{margin-top: 50px !important;margin-bottom: 20px !important;}" element_css_xs=".vc_custom_1517817973848{margin-top: 40px !important;margin-bottom: 10px !important;}"][vc_column][vc_row_inner][vc_column_inner offset="vc_col-lg-6 vc_col-md-8"][vc_custom_heading text="Let’s Get In Touch!" use_theme_fonts="yes" font_weight="700" css=".vc_custom_1523447524273{margin-bottom: 25px !important;}"][vc_custom_heading text="It would be great to hear from you! If you got any questions, please do not hesitate to send us a message." font_container="tag:p|text_align:left" use_theme_fonts="yes" css=".vc_custom_1523447534657{margin-bottom: 35px !important;}"][/vc_column_inner][/vc_row_inner][vc_row_inner el_id="1542439673137-f3dcc35b-2d96"][vc_column_inner css=".vc_custom_1517818064129{margin-bottom: 30px !important;}" offset="vc_col-lg-4 vc_col-md-4" el_id="1542439673256-9dfcc8e8-f2d7"][pgscore_info_box_2 content_alignment="left" title_el="h5" description_color="#888888" icon_source="font" icon_color="#f53d03" icon_type="flaticon" icon_flaticon="glyph-icon pgsicon-ecommerce-placeholder-2" layout="style_1" title="ADDRESS" icon_position="left" add_anchor="" anchor_link="" title_color="#323232" info_content="1635 Franklin Street Montgomery,
Near Sherwood Mall. AL 36104" background_options="border" title_hover_color="#04d39f" backround_img="" element_back_color="#F5F5F5" element_hover_color="#323232" border_width="5" border_color="#F5F5F5" border_hover_color="#04d39f" icon_style="default" icon_size="md" add_animation="true" icon_shape="square" icon_background_color="#ccc" icon_border_color="#ccc" icon_image="" element_css="" element_id="" element_class="" icon_fontawesome="fa fa-info-circle" icon_openiconic="vc-oi vc-oi-dial" icon_typicons="typcn typcn-adjust-brightness" icon_entypo="entypo-icon entypo-icon-note" icon_linecons="vc_li vc_li-heart" icon_monosocial="vc-mono vc-mono-fivehundredpx" icon_material="vc-material vc-material-cake" icon_pixelicons="vc_pixel_icon vc_pixel_icon-alert"][/vc_column_inner][vc_column_inner css=".vc_custom_1517818072746{margin-bottom: 30px !important;}" offset="vc_col-lg-4 vc_col-md-4" el_id="1542439673395-b517f2df-e8d4"][pgscore_info_box_2 content_alignment="left" title_el="h5" description_color="#888888" icon_source="font" icon_color="#f53d03" icon_type="flaticon" icon_flaticon="glyph-icon pgsicon-ecommerce-phone-call" layout="style_1" title="ADDRESS" icon_position="left" add_anchor="" anchor_link="" title_color="#323232" background_options="border" title_hover_color="#04d39f" backround_img="" element_back_color="#F5F5F5" element_hover_color="#323232" border_width="5" border_color="#F5F5F5" border_hover_color="#04d39f" icon_style="default" icon_size="md" add_animation="true" icon_shape="square" icon_background_color="#ccc" icon_border_color="#ccc" icon_image="" element_css="" element_id="" element_class="" icon_fontawesome="fa fa-info-circle" icon_openiconic="vc-oi vc-oi-dial" icon_typicons="typcn typcn-adjust-brightness" icon_entypo="entypo-icon entypo-icon-note" icon_linecons="vc_li vc_li-heart" icon_monosocial="vc-mono vc-mono-fivehundredpx" icon_material="vc-material vc-material-cake" icon_pixelicons="vc_pixel_icon vc_pixel_icon-alert" info_content="126-632-2345
Mon to Fri 09:00 am – 6:30 pm"][/vc_column_inner][vc_column_inner css=".vc_custom_1517818080822{margin-bottom: 30px !important;}" offset="vc_col-lg-4 vc_col-md-4" el_id="1542439673508-07260555-9047"][pgscore_info_box_2 content_alignment="left" title_el="h5" description_color="#888888" icon_source="font" icon_color="#f53d03" icon_type="flaticon" icon_flaticon="glyph-icon pgsicon-ecommerce-e-mail-envelope" layout="style_1" title="SUPPORT" icon_position="left" add_anchor="" anchor_link="" title_color="#323232" background_options="border" title_hover_color="#04d39f" backround_img="" element_back_color="#F5F5F5" element_hover_color="#323232" border_width="5" border_color="#F5F5F5" border_hover_color="#04d39f" icon_style="default" icon_size="md" add_animation="true" icon_shape="square" icon_background_color="#ccc" icon_border_color="#ccc" icon_image="" element_css="" element_id="" element_class="" icon_fontawesome="fa fa-info-circle" icon_openiconic="vc-oi vc-oi-dial" icon_typicons="typcn typcn-adjust-brightness" icon_entypo="entypo-icon entypo-icon-note" icon_linecons="vc_li vc_li-heart" icon_monosocial="vc-mono vc-mono-fivehundredpx" icon_material="vc-material vc-material-cake" icon_pixelicons="vc_pixel_icon vc_pixel_icon-alert" info_content="support@ciyashop.com
24 x 7 Online Support"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]
CONTENT',
);
