<?php
/**
 * full widht 3 box
 *
 * @package CiyaShop
 */

return array(
	'name'              => esc_html__( 'full widht 3 box', 'ciyashop' ),
	'template_category' => esc_html__( 'Contact Info', 'ciyashop' ),
	'disabled'          => true, // Disable it to not show in the default tab.
	'content'           => '<<<CONTENT
[vc_row full_width="stretch_row_content_no_spaces" pgscore_enable_responsive_settings="true" el_id="1542363857464-ad193ca1-d8d8" css=".vc_custom_1518693379006{margin-bottom: 70px !important;}" element_css_md=".vc_custom_1518693379009{margin-bottom: 60px !important;}" element_css_sm=".vc_custom_1518693379012{margin-bottom: 50px !important;}" element_css_xs=".vc_custom_1518693379015{margin-bottom: 40px !important;}"][vc_column offset="vc_col-lg-4 vc_col-md-4" el_id="1542363857533-9095315f-ab65"][pgscore_info_box_2 content_alignment="center" title_el="h5" icon_size="lg" icon_source="font" icon_type="flaticon" icon_flaticon="glyph-icon pgsicon-ecommerce-placeholder-2" layout="style_1" title="OUR LOCATION" element_css=".vc_custom_1544099723652{padding-top: 65px !important;padding-right: 20px !important;padding-bottom: 65px !important;padding-left: 20px !important;background-color: #f1dc00 !important;}" icon_position="left" add_anchor="" anchor_link="" title_color="#323232" info_content="1635 Franklin Street Montgomery,
Near Sherwood Mall. AL 36104" description_color="#323232" background_options="border" title_hover_color="#04d39f" backround_img="" element_back_color="#F5F5F5" element_hover_color="#323232" border_width="5" border_color="#F5F5F5" border_hover_color="#04d39f" icon_style="default" add_animation="true" icon_shape="square" icon_background_color="#ccc" icon_border_color="#ccc" icon_image="" icon_color="#323232" element_id="" element_class="" icon_fontawesome="fa fa-info-circle" icon_openiconic="vc-oi vc-oi-dial" icon_typicons="typcn typcn-adjust-brightness" icon_entypo="entypo-icon entypo-icon-note" icon_linecons="vc_li vc_li-heart" icon_monosocial="vc-mono vc-mono-fivehundredpx" icon_material="vc-material vc-material-cake" icon_pixelicons="vc_pixel_icon vc_pixel_icon-alert"][/vc_column][vc_column offset="vc_col-lg-4 vc_col-md-4" el_id="1542363857651-ad797be6-97f0"][pgscore_info_box_2 content_alignment="center" title_el="h5" icon_size="lg" icon_source="font" icon_type="flaticon" icon_flaticon="glyph-icon pgsicon-ecommerce-phone-call" layout="style_1" title="CALL US" element_css=".vc_custom_1544099746648{padding-top: 65px !important;padding-right: 20px !important;padding-bottom: 65px !important;padding-left: 20px !important;background-color: #e0cd03 !important;}" icon_position="left" add_anchor="" anchor_link="" title_color="#323232" info_content="126-632-2345
857-778-1265" description_color="#323232" background_options="border" title_hover_color="#04d39f" backround_img="" element_back_color="#F5F5F5" element_hover_color="#323232" border_width="5" border_color="#F5F5F5" border_hover_color="#04d39f" icon_style="default" add_animation="true" icon_shape="square" icon_background_color="#ccc" icon_border_color="#ccc" icon_image="" icon_color="#323232" element_id="" element_class="" icon_fontawesome="fa fa-info-circle" icon_openiconic="vc-oi vc-oi-dial" icon_typicons="typcn typcn-adjust-brightness" icon_entypo="entypo-icon entypo-icon-note" icon_linecons="vc_li vc_li-heart" icon_monosocial="vc-mono vc-mono-fivehundredpx" icon_material="vc-material vc-material-cake" icon_pixelicons="vc_pixel_icon vc_pixel_icon-alert"][/vc_column][vc_column offset="vc_col-lg-4 vc_col-md-4" el_id="1542363857718-173d0d0d-7a42"][pgscore_info_box_2 content_alignment="center" title_el="h5" icon_size="lg" icon_source="font" icon_type="flaticon" icon_flaticon="glyph-icon pgsicon-ecommerce-online-shop-3" layout="style_1" title="CONNECT ONLINE" element_css=".vc_custom_1544099777297{padding-top: 65px !important;padding-right: 20px !important;padding-bottom: 65px !important;padding-left: 20px !important;background-color: #d6c402 !important;}" icon_position="left" add_anchor="" anchor_link="" title_color="#323232" info_content="support@ciyashop.com
gethelp@ciyashop.com" description_color="#323232" background_options="border" title_hover_color="#04d39f" backround_img="" element_back_color="#F5F5F5" element_hover_color="#323232" border_width="5" border_color="#F5F5F5" border_hover_color="#04d39f" icon_style="default" add_animation="true" icon_shape="square" icon_background_color="#ccc" icon_border_color="#ccc" icon_image="" icon_color="#323232" element_id="" element_class="" icon_fontawesome="fa fa-info-circle" icon_openiconic="vc-oi vc-oi-dial" icon_typicons="typcn typcn-adjust-brightness" icon_entypo="entypo-icon entypo-icon-note" icon_linecons="vc_li vc_li-heart" icon_monosocial="vc-mono vc-mono-fivehundredpx" icon_material="vc-material vc-material-cake" icon_pixelicons="vc_pixel_icon vc_pixel_icon-alert"][/vc_column][/vc_row]
CONTENT',
);
