<?php
/**
 * Contact Info left Map
 *
 * @package CiyaShop
 */

return array(
	'name'              => esc_html__( 'Contact Info left Map', 'ciyashop' ),
	'template_category' => esc_html__( 'Contact Info', 'ciyashop' ),
	'disabled'          => true, // Disable it to not show in the default tab.
	'content'           => '<<<CONTENT
[vc_row equal_height="yes" content_placement="middle" pgscore_enable_responsive_settings="true" el_id="1522841153209-4b18b3ab-f1f0" css=".vc_custom_1523256180402{margin-top: 100px !important;margin-bottom: 60px !important;}" element_css_md=".vc_custom_1523256180406{margin-top: 80px !important;margin-bottom: 40px !important;}" element_css_sm=".vc_custom_1523256180409{margin-top: 60px !important;margin-bottom: 20px !important;}" element_css_xs=".vc_custom_1523256180412{margin-top: 40px !important;margin-bottom: 0px !important;}"][vc_column width="1/2" css=".vc_custom_1522841517137{margin-bottom: 40px !important;}"][vc_gmaps link="#E-8_JTNDaWZyYW1lJTIwc3JjJTNEJTIyaHR0cHMlM0ElMkYlMkZ3d3cuZ29vZ2xlLmNvbSUyRm1hcHMlMkZlbWJlZCUzRnBiJTNEJTIxMW0xOCUyMTFtMTIlMjExbTMlMjExZDYzMDQuODI5OTg2MTMxMjcxJTIxMmQtMTIyLjQ3NDY5NjgwMzMwOTIlMjEzZDM3LjgwMzc0NzUyMTYwNDQzJTIxMm0zJTIxMWYwJTIxMmYwJTIxM2YwJTIxM20yJTIxMWkxMDI0JTIxMmk3NjglMjE0ZjEzLjElMjEzbTMlMjExbTIlMjExczB4ODA4NTg2ZTYzMDI2MTVhMSUyNTNBMHg4NmJkMTMwMjUxNzU3YzAwJTIxMnNTdG9yZXklMkJBdmUlMjUyQyUyQlNhbiUyQkZyYW5jaXNjbyUyNTJDJTJCQ0ElMkI5NDEyOSUyMTVlMCUyMTNtMiUyMTFzZW4lMjEyc3VzJTIxNHYxNDM1ODI2NDMyMDUxJTIyJTIwd2lkdGglM0QlMjI2MDAlMjIlMjBoZWlnaHQlM0QlMjI0NTAlMjIlMjBmcmFtZWJvcmRlciUzRCUyMjAlMjIlMjBzdHlsZSUzRCUyMmJvcmRlciUzQTAlMjIlMjBhbGxvd2Z1bGxzY3JlZW4lM0UlM0MlMkZpZnJhbWUlM0U=" css=".vc_custom_1522930671777{margin-bottom: 0px !important;border-radius: 20px !important;}" el_class="overflow-h"][/vc_column][vc_column width="1/2" css=".vc_custom_1522841508089{margin-bottom: 40px !important;}"][vc_custom_heading text="Let’s Get In Touch!" use_theme_fonts="yes" css=".vc_custom_1523597462044{margin-bottom: 30px !important;}"][vc_column_text]It would be great to hear from you! If you got any questions, please do not hesitate to send us a message. We are looking forward to hearing from you! We reply within 24 hours!
[/vc_column_text][pgscore_info_box_2 icon_position="left" title_el="h6" title_color="#969696" description_color="#969696" icon_size="xs" icon_source="font" icon_color="#00a4d3" icon_fontawesome="fa fa-envelope-o" layout="style_2" element_css=".vc_custom_1544105246865{margin-bottom: 30px !important;}" content_alignment="center" add_anchor="" anchor_link="" info_content="support@ciyashop.com" background_options="border" title_hover_color="#04d39f" backround_img="" element_back_color="#F5F5F5" element_hover_color="#323232" border_width="5" border_color="#F5F5F5" border_hover_color="#04d39f" icon_style="default" add_animation="true" icon_shape="square" icon_background_color="#ccc" icon_border_color="#ccc" icon_image="" element_id="" element_class="" icon_type="fontawesome" icon_openiconic="vc-oi vc-oi-dial" icon_typicons="typcn typcn-adjust-brightness" icon_entypo="entypo-icon entypo-icon-note" icon_linecons="vc_li vc_li-heart" icon_monosocial="vc-mono vc-mono-fivehundredpx" icon_material="vc-material vc-material-cake" icon_pixelicons="vc_pixel_icon vc_pixel_icon-alert" icon_flaticon="glyph-icon flaticon-right-arrow-1"][pgscore_info_box_2 icon_position="left" title_el="h6" title_color="#969696" description_color="#969696" icon_size="xs" icon_source="font" icon_color="#00a4d3" icon_fontawesome="fa fa-phone" layout="style_2" element_css=".vc_custom_1544105268623{margin-bottom: 30px !important;}" content_alignment="center" add_anchor="" anchor_link="" info_content="126-632-2345" background_options="border" title_hover_color="#04d39f" backround_img="" element_back_color="#F5F5F5" element_hover_color="#323232" border_width="5" border_color="#F5F5F5" border_hover_color="#04d39f" icon_style="default" add_animation="true" icon_shape="square" icon_background_color="#ccc" icon_border_color="#ccc" icon_image="" element_id="" element_class="" icon_type="fontawesome" icon_openiconic="vc-oi vc-oi-dial" icon_typicons="typcn typcn-adjust-brightness" icon_entypo="entypo-icon entypo-icon-note" icon_linecons="vc_li vc_li-heart" icon_monosocial="vc-mono vc-mono-fivehundredpx" icon_material="vc-material vc-material-cake" icon_pixelicons="vc_pixel_icon vc_pixel_icon-alert" icon_flaticon="glyph-icon flaticon-right-arrow-1"][pgscore_info_box_2 icon_position="left" title_el="h6" title_color="#969696" description_color="#969696" icon_size="xs" icon_source="font" icon_color="#00a4d3" icon_fontawesome="fa fa-map-marker" layout="style_2" element_css=".vc_custom_1544105291958{margin-bottom: 30px !important;}" content_alignment="center" add_anchor="" anchor_link="" info_content="Porterfield 508 Virginia Street Chicago, Opp M.
Alexander Building. IL 60653" background_options="border" title_hover_color="#04d39f" backround_img="" element_back_color="#F5F5F5" element_hover_color="#323232" border_width="5" border_color="#F5F5F5" border_hover_color="#04d39f" icon_style="default" add_animation="true" icon_shape="square" icon_background_color="#ccc" icon_border_color="#ccc" icon_image="" element_id="" element_class="" icon_type="fontawesome" icon_openiconic="vc-oi vc-oi-dial" icon_typicons="typcn typcn-adjust-brightness" icon_entypo="entypo-icon entypo-icon-note" icon_linecons="vc_li vc_li-heart" icon_monosocial="vc-mono vc-mono-fivehundredpx" icon_material="vc-material vc-material-cake" icon_pixelicons="vc_pixel_icon vc_pixel_icon-alert" icon_flaticon="glyph-icon flaticon-right-arrow-1"][pgscore_social_icons style="flat-color" shape="rounded" size="small" list_items="%5B%7B%22link%22%3A%22url%3A%2523%7C%7C%7C%22%2C%22icon%22%3A%22fa%20fa-facebook%22%7D%2C%7B%22link%22%3A%22url%3A%2523%7C%7C%7C%22%2C%22icon%22%3A%22fa%20fa-twitter%22%7D%2C%7B%22link%22%3A%22url%3A%2523%7C%7C%7C%22%2C%22icon%22%3A%22fa%20fa-google-plus%22%7D%2C%7B%22link%22%3A%22url%3A%2523%7C%7C%7C%22%2C%22icon%22%3A%22fa%20fa-linkedin%22%7D%2C%7B%22link%22%3A%22url%3A%2523%7C%7C%7C%22%2C%22icon%22%3A%22fa%20fa-pinterest%22%7D%5D" element_css=".vc_custom_1522929594637{margin-top: 20px !important;margin-left: 45px !important;}"][/vc_column][/vc_row]
CONTENT',
);
