<?php
/**
 * Left Info with Map
 *
 * @package CiyaShop
 */

return array(
	'name'              => esc_html__( 'Left Info with Map', 'ciyashop' ),
	'template_category' => esc_html__( 'Contact Info', 'ciyashop' ),
	'disabled'          => true, // Disable it to not show in the default tab.
	'content'           => '<<<CONTENT
[vc_row pgscore_enable_responsive_settings="true" el_id="1519130008695-fa0d2f24-c684" css=".vc_custom_1526392342930{margin-top: 50px !important;margin-bottom: 80px !important;}" element_css_md=".vc_custom_1526392342931{margin-top: 30px !important;margin-bottom: 60px !important;}" element_css_sm=".vc_custom_1526392342933{margin-top: 20px !important;margin-bottom: 50px !important;}" element_css_xs=".vc_custom_1526392342933{margin-top: 10px !important;margin-bottom: 40px !important;}" el_class="d-lg-flex"][vc_column css=".vc_custom_1526392355267{padding-top: 30px !important;}" offset="vc_col-lg-6 vc_col-md-6" el_class="order-lg-2"][vc_gmaps link="#E-8_JTNDaWZyYW1lJTIwc3JjJTNEJTIyaHR0cHMlM0ElMkYlMkZ3d3cuZ29vZ2xlLmNvbSUyRm1hcHMlMkZlbWJlZCUzRnBiJTNEJTIxMW0xOCUyMTFtMTIlMjExbTMlMjExZDYzMDQuODI5OTg2MTMxMjcxJTIxMmQtMTIyLjQ3NDY5NjgwMzMwOTIlMjEzZDM3LjgwMzc0NzUyMTYwNDQzJTIxMm0zJTIxMWYwJTIxMmYwJTIxM2YwJTIxM20yJTIxMWkxMDI0JTIxMmk3NjglMjE0ZjEzLjElMjEzbTMlMjExbTIlMjExczB4ODA4NTg2ZTYzMDI2MTVhMSUyNTNBMHg4NmJkMTMwMjUxNzU3YzAwJTIxMnNTdG9yZXklMkJBdmUlMjUyQyUyQlNhbiUyQkZyYW5jaXNjbyUyNTJDJTJCQ0ElMkI5NDEyOSUyMTVlMCUyMTNtMiUyMTFzZW4lMjEyc3VzJTIxNHYxNDM1ODI2NDMyMDUxJTIyJTIwd2lkdGglM0QlMjI2MDAlMjIlMjBoZWlnaHQlM0QlMjI0NTAlMjIlMjBmcmFtZWJvcmRlciUzRCUyMjAlMjIlMjBzdHlsZSUzRCUyMmJvcmRlciUzQTAlMjIlMjBhbGxvd2Z1bGxzY3JlZW4lM0UlM0MlMkZpZnJhbWUlM0U=" css=".vc_custom_1519130145212{margin-bottom: 0px !important;}"][/vc_column][vc_column css=".vc_custom_1526392363267{padding-top: 30px !important;padding-right: 10% !important;}" offset="vc_col-lg-6 vc_col-md-6" el_class="order-lg-1"][vc_custom_heading text="Contact Information :" font_container="tag:h2|text_align:left|color:%23ae4b5c" use_theme_fonts="yes" font_weight="500" css=".vc_custom_1519134775520{margin-bottom: 20px !important;}"][vc_column_text css=".vc_custom_1519130697262{border-bottom-width: 1px !important;padding-bottom: 25px !important;border-bottom-color: #e8e8e8 !important;border-bottom-style: solid !important;}"]Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut.[/vc_column_text][pgscore_info_box_2 icon_position="left" title_el="h6" description_color="#888888" icon_size="xs" icon_source="font" icon_color="#ae4b5c" icon_fontawesome="fa fa-home" layout="style_2" title="ADDRESS :" element_css=".vc_custom_1544107996555{margin-bottom: 20px !important;}" content_alignment="center" add_anchor="" anchor_link="" title_color="#323232" info_content="1635 Franklin Street Montgomery,
Near Sherwood Mall. AL 36104" background_options="border" title_hover_color="#04d39f" backround_img="" element_back_color="#F5F5F5" element_hover_color="#323232" border_width="5" border_color="#F5F5F5" border_hover_color="#04d39f" icon_style="default" add_animation="true" icon_shape="square" icon_background_color="#ccc" icon_border_color="#ccc" icon_image="" element_id="" element_class="" icon_type="fontawesome" icon_openiconic="vc-oi vc-oi-dial" icon_typicons="typcn typcn-adjust-brightness" icon_entypo="entypo-icon entypo-icon-note" icon_linecons="vc_li vc_li-heart" icon_monosocial="vc-mono vc-mono-fivehundredpx" icon_material="vc-material vc-material-cake" icon_pixelicons="vc_pixel_icon vc_pixel_icon-alert" icon_flaticon="glyph-icon flaticon-right-arrow-1"][pgscore_info_box_2 icon_position="left" title_el="h6" description_color="#888888" icon_size="xs" icon_source="font" icon_color="#ae4b5c" icon_fontawesome="fa fa-mobile" layout="style_2" title="CONTACT :" element_css=".vc_custom_1544108004651{margin-bottom: 20px !important;}" content_alignment="center" add_anchor="" anchor_link="" title_color="#323232" info_content="126-632-2345
Mon to Fri 09:00 am – 6:30 pm" background_options="border" title_hover_color="#04d39f" backround_img="" element_back_color="#F5F5F5" element_hover_color="#323232" border_width="5" border_color="#F5F5F5" border_hover_color="#04d39f" icon_style="default" add_animation="true" icon_shape="square" icon_background_color="#ccc" icon_border_color="#ccc" icon_image="" element_id="" element_class="" icon_type="fontawesome" icon_openiconic="vc-oi vc-oi-dial" icon_typicons="typcn typcn-adjust-brightness" icon_entypo="entypo-icon entypo-icon-note" icon_linecons="vc_li vc_li-heart" icon_monosocial="vc-mono vc-mono-fivehundredpx" icon_material="vc-material vc-material-cake" icon_pixelicons="vc_pixel_icon vc_pixel_icon-alert" icon_flaticon="glyph-icon flaticon-right-arrow-1"][pgscore_info_box_2 icon_position="left" title_el="h6" description_color="#888888" icon_size="xs" icon_source="font" icon_color="#ae4b5c" icon_fontawesome="fa fa-headphones" layout="style_2" title="SUPPORT :" content_alignment="center" add_anchor="" anchor_link="" title_color="#323232" info_content="support@ciyashop.com
24 x 7 Online Support" background_options="border" title_hover_color="#04d39f" backround_img="" element_back_color="#F5F5F5" element_hover_color="#323232" border_width="5" border_color="#F5F5F5" border_hover_color="#04d39f" icon_style="default" add_animation="true" icon_shape="square" icon_background_color="#ccc" icon_border_color="#ccc" icon_image="" element_css="" element_id="" element_class="" icon_type="fontawesome" icon_openiconic="vc-oi vc-oi-dial" icon_typicons="typcn typcn-adjust-brightness" icon_entypo="entypo-icon entypo-icon-note" icon_linecons="vc_li vc_li-heart" icon_monosocial="vc-mono vc-mono-fivehundredpx" icon_material="vc-material vc-material-cake" icon_pixelicons="vc_pixel_icon vc_pixel_icon-alert" icon_flaticon="glyph-icon flaticon-right-arrow-1"][/vc_column][/vc_row]
CONTENT',
);
