<?php
/**
 * Counter Only Number
 *
 * @package CiyaShop
 */

return array(
	'name'              => esc_html__( 'Counter Only Number', 'ciyashop' ),
	'template_category' => esc_html__( 'Counter', 'ciyashop' ),
	'disabled'          => true, // Disable it to not show in the default tab.
	'content'           => <<<CONTENT
[vc_row full_width="stretch_row" equal_height="yes" content_placement="middle" pgscore_enable_responsive_settings="true" el_id="1517631246054-57f82883-577b" css=".vc_custom_1543240074330{padding-top: 80px !important;padding-bottom: 50px !important;background-color: #f5f5f5 !important;}" element_css_sm=".vc_custom_1543240074333{padding-top: 50px !important;padding-bottom: 0px !important;}" element_css_xs=".vc_custom_1543240074334{padding-top: 40px !important;padding-bottom: 0px !important;}" element_css_md=".vc_custom_1543240074332{padding-top: 60px !important;padding-bottom: 30px !important;}"][vc_column css=".vc_custom_1526304669024{padding-top: 0px !important;padding-bottom: 30px !important;}" el_class="order-lg-2" offset="vc_col-lg-6 vc_col-md-6"][vc_single_image source="external_link" custom_src="https://ciyashop.potenzaglobalsolutions.com/goggles/wp-content/uploads/sites/64/2018/02/about-img.jpg"][/vc_column][vc_column pgscore_enable_responsive_settings="true" css=".vc_custom_1543239254321{margin-bottom: 30px !important;padding-top: 0px !important;}" el_class="order-lg-1" offset="vc_col-lg-6 vc_col-md-6" element_css_xs=".vc_custom_1543239254330{margin-bottom: 0px !important;}"][vc_custom_heading text="Founded in 2017" font_container="tag:h3|text_align:left" use_theme_fonts="yes" font_weight="700" css=".vc_custom_1517635239297{margin-bottom: 15px !important;}"][vc_column_text]<strong>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.</strong>
It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy.[/vc_column_text][vc_row_inner el_id="1542438077516-fa426cd2-604a"][vc_column_inner width="1/3" el_id="1542438077627-acfe701d-5ae7"][pgscore_counter counter_icon_disable="true" counter_alighnment="left" counter_title_color="#555555" counter_title_font_size="16" counter_number="2050" counter_number_font_size="40" counter_number_color="#f53d03" counter_title="Online Sellings" element_css=".vc_custom_1543494906143{padding-bottom: 30px !important;}"][/vc_column_inner][vc_column_inner width="1/3" el_id="1542438077778-f7f00718-52e0"][pgscore_counter counter_icon_disable="true" counter_alighnment="left" counter_title_color="#555555" counter_title_font_size="16" counter_number="1075" counter_number_font_size="40" counter_number_color="#f53d03" counter_title="Happy Clients" element_css=".vc_custom_1543494944427{padding-bottom: 30px !important;}"][/vc_column_inner][vc_column_inner width="1/3" el_id="1542438077886-6b65cb3c-90ce"][pgscore_counter counter_icon_disable="true" counter_alighnment="left" counter_title_color="#555555" counter_title_font_size="16" counter_number="170" counter_number_font_size="40" counter_number_color="#f53d03" counter_title="Award Won" element_css=".vc_custom_1543494954996{padding-bottom: 30px !important;}"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]

CONTENT
);
