<?php
/**
 * Counter Top Icon Rounded
 *
 * @package CiyaShop
 */

return array(
	'name'              => esc_html__( 'Counter Top Icon Rounded', 'ciyashop' ),
	'template_category' => esc_html__( 'Counter', 'ciyashop' ),
	'disabled'          => true, // Disable it to not show in the default tab.
	'content'           => '<<<CONTENT
[vc_row full_width="stretch_row" pgscore_bg_type="row-background-dark" enable_first_overlay="true" first_overlay_opacity="80" first_background_color="#000000" pgscore_enable_responsive_settings="true" el_id="1523971202020-163178ac-a786" css=".vc_custom_1524055477630{padding-top: 80px !important;padding-bottom: 50px !important;background-image: url(https://ciyashop.potenzaglobalsolutions.com/petstore/wp-content/uploads/sites/17/2018/04/counter-bg.jpg?id=534) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}" element_css_md=".vc_custom_1524055477632{padding-top: 60px !important;padding-bottom: 30px !important;}" element_css_sm=".vc_custom_1524055477633{padding-top: 50px !important;padding-bottom: 20px !important;}" element_css_xs=".vc_custom_1524055477634{padding-top: 40px !important;padding-bottom: 10px !important;}"][vc_column css=".vc_custom_1523972514975{padding-top: 0px !important;}"][vc_row_inner][vc_column_inner offset="vc_col-lg-offset-2 vc_col-lg-8"][vc_custom_heading text="Some Interesting Facts" font_container="tag:h2|text_align:center" use_theme_fonts="yes"][vc_column_text css=".vc_custom_1523973002173{margin-bottom: 40px !important;}"]
<p style="text-align: center;">No one rejects dislikes or avoids pleasure itself because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful.</p>
[/vc_column_text][/vc_column_inner][/vc_row_inner][vc_row_inner][vc_column_inner el_class="text-center" width="1/4" offset="vc_col-xs-6" css=".vc_custom_1542975224631{margin-bottom: 30px !important;}"][pgscore_counter counter_style="style_2" counter_alighnment="center" counter_title_color="#ffffff" counter_title_font_size="18" counter_number="380" counter_number_font_size="40" counter_number_color="#ffffff" counter_background_color="#323232" counter_icon_color="#ffffff" icon_fontawesome="fa fa-paw" counter_title="Veterinary"][/vc_column_inner][vc_column_inner el_class="text-center" width="1/4" offset="vc_col-xs-6" css=".vc_custom_1542975282937{margin-bottom: 30px !important;}"][pgscore_counter counter_style="style_2" counter_alighnment="center" counter_title_color="#ffffff" counter_title_font_size="18" counter_number="275" counter_number_font_size="40" counter_number_color="#ffffff" counter_background_color="#323232" counter_icon_color="#ffffff" icon_fontawesome="fa fa-users" counter_title="Pet Adoption"][/vc_column_inner][vc_column_inner el_class="text-center" width="1/4" offset="vc_col-xs-6" css=".vc_custom_1542975358617{margin-bottom: 30px !important;}"][pgscore_counter counter_style="style_2" counter_alighnment="center" counter_title_color="#ffffff" counter_title_font_size="18" counter_number="595" counter_number_font_size="40" counter_number_color="#ffffff" counter_background_color="#323232" counter_icon_color="#ffffff" icon_type="material" icon_material="vc-material vc-material-directions_walk" counter_title="Dog Walking"][/vc_column_inner][vc_column_inner el_class="text-center" width="1/4" offset="vc_col-xs-6" css=".vc_custom_1542975367977{margin-bottom: 30px !important;}"][pgscore_counter counter_style="style_2" counter_alighnment="center" counter_title_color="#ffffff" counter_title_font_size="18" counter_number="260" counter_number_font_size="40" counter_number_color="#ffffff" counter_background_color="#323232" counter_icon_color="#ffffff" icon_fontawesome="fa fa-scissors" counter_title="Pet Grooming"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]

CONTENT',
);
