<?php
/**
 * Contact Form with Dark BG
 *
 * @package CiyaShop
 */

return array(
	'name'              => esc_html__( 'Contact Form with Dark BG', 'ciyashop' ),
	'template_category' => esc_html__( 'Form', 'ciyashop' ),
	'disabled'          => true, // Disable it to not show in the default tab.
	'content'           => '<<<CONTENT
<p>[vc_row full_width="stretch_row" equal_height="yes" content_placement="middle" pgscore_bg_type="row-background-dark" pgscore_enable_responsive_settings="true" pgscore_enable_overlay="true" enable_first_overlay="true" first_overlay_opacity="80" first_background_color="#000000" el_id="1524654007107-ef565066-1fc4" css=".vc_custom_1545207820178{padding-top: 120px !important;padding-bottom: 80px !important;background-image: url(http://ciyashop.potenzaglobalsolutions.com/art-gallery/wp-content/uploads/sites/19/2018/04/contact-bg.jpg?id=485) !important;}" element_css_md=".vc_custom_1545207820180{padding-top: 80px !important;padding-bottom: 40px !important;}" element_css_sm=".vc_custom_1545207820181{padding-top: 60px !important;padding-bottom: 20px !important;}" element_css_xs=".vc_custom_1545207820181{padding-top: 40px !important;padding-bottom: 0px !important;}" pgscore_overlay_color="rgba(0,0,0,0.8)"][vc_column css=".vc_custom_1525068737865{margin-bottom: 40px !important;padding-top: 0px !important;}" offset="vc_col-lg-6 vc_col-md-5" el_id="1545206307420-661bf6ed-6b3a"][vc_custom_heading text="Call Us" font_container="tag:h6|text_align:left" use_theme_fonts="yes"][vc_custom_heading text="126-632-2345" font_container="tag:h1|text_align:left" google_fonts="font_family:Lato%3A100%2C100italic%2C300%2C300italic%2Cregular%2Citalic%2C700%2C700italic%2C900%2C900italic|font_style:400%20regular%3A400%3Anormal" css=".vc_custom_1524656550836{margin-bottom: 0px !important;}"][vc_row_inner el_id="1545206307448-e91e1c59-bea8"][vc_column_inner el_id="1545206307457-a2235dd5-37a4"][pgscore_info_box_2 icon_position="left" title_el="h6" title_color="#ffffff" description_color="#ffffff" icon_size="xs" icon_source="font" icon_color="#ffffff" icon_fontawesome="fa fa-map-marker" layout="style_2" title="Office address" element_css=".vc_custom_1544160616040{margin-top: 30px !important;margin-bottom: 30px !important;}" content_alignment="center" add_anchor="" anchor_link="" info_content="1635 Franklin Street Montgomery, Near<br />
Sherwood Mall. AL 36104" background_options="border" title_hover_color="#04d39f" backround_img="" element_back_color="#F5F5F5" element_hover_color="#323232" border_width="5" border_color="#F5F5F5" border_hover_color="#04d39f" icon_style="default" add_animation="true" icon_shape="square" icon_background_color="#ccc" icon_border_color="#ccc" icon_image="" element_id="" element_class="" icon_type="fontawesome" icon_openiconic="vc-oi vc-oi-dial" icon_typicons="typcn typcn-adjust-brightness" icon_entypo="entypo-icon entypo-icon-note" icon_linecons="vc_li vc_li-heart" icon_monosocial="vc-mono vc-mono-fivehundredpx" icon_material="vc-material vc-material-cake" icon_pixelicons="vc_pixel_icon vc_pixel_icon-alert" icon_flaticon="glyph-icon flaticon-right-arrow-1"][pgscore_info_box_2 icon_position="left" title_el="h6" title_color="#ffffff" description_color="#ffffff" icon_size="xs" icon_source="font" icon_color="#ffffff" icon_fontawesome="fa fa-envelope-o" layout="style_2" title="Message" element_css=".vc_custom_1544160627618{margin-bottom: 30px !important;}" content_alignment="center" add_anchor="" anchor_link="" info_content="support@ciyashop.com<br />
gethelp@ciyashop.com" background_options="border" title_hover_color="#04d39f" backround_img="" element_back_color="#F5F5F5" element_hover_color="#323232" border_width="5" border_color="#F5F5F5" border_hover_color="#04d39f" icon_style="default" add_animation="true" icon_shape="square" icon_background_color="#ccc" icon_border_color="#ccc" icon_image="" element_id="" element_class="" icon_type="fontawesome" icon_openiconic="vc-oi vc-oi-dial" icon_typicons="typcn typcn-adjust-brightness" icon_entypo="entypo-icon entypo-icon-note" icon_linecons="vc_li vc_li-heart" icon_monosocial="vc-mono vc-mono-fivehundredpx" icon_material="vc-material vc-material-cake" icon_pixelicons="vc_pixel_icon vc_pixel_icon-alert" icon_flaticon="glyph-icon flaticon-right-arrow-1"][pgscore_info_box_2 icon_position="left" title_el="h6" title_color="#ffffff" description_color="#ffffff" icon_size="xs" icon_source="font" icon_color="#ffffff" icon_fontawesome="fa fa-clock-o" layout="style_2" title="Opening hours" element_css=".vc_custom_1544160647303{margin-bottom: 30px !important;}" content_alignment="center" add_anchor="" anchor_link="" info_content="Mon-Fri: 8am to 6pm<br />
Sat-sun: Off" background_options="border" title_hover_color="#04d39f" backround_img="" element_back_color="#F5F5F5" element_hover_color="#323232" border_width="5" border_color="#F5F5F5" border_hover_color="#04d39f" icon_style="default" add_animation="true" icon_shape="square" icon_background_color="#ccc" icon_border_color="#ccc" icon_image="" element_id="" element_class="" icon_type="fontawesome" icon_openiconic="vc-oi vc-oi-dial" icon_typicons="typcn typcn-adjust-brightness" icon_entypo="entypo-icon entypo-icon-note" icon_linecons="vc_li vc_li-heart" icon_monosocial="vc-mono vc-mono-fivehundredpx" icon_material="vc-material vc-material-cake" icon_pixelicons="vc_pixel_icon vc_pixel_icon-alert" icon_flaticon="glyph-icon flaticon-right-arrow-1"][/vc_column_inner][/vc_row_inner][/vc_column][vc_column css=".vc_custom_1525068742968{margin-bottom: 40px !important;padding-top: 0px !important;}" offset="vc_col-lg-6 vc_col-md-7" el_id="1545206307485-2c049ca6-9637"][vc_row_inner css=".vc_custom_1525069692255{margin-right: 0px !important;margin-left: 0px !important;}"][vc_column_inner css=".vc_custom_1525070188447{margin-bottom: -16px !important;padding-top: 5em !important;padding-right: 2em !important;padding-bottom: 5em !important;padding-left: 2em !important;background-color: #2a4670 !important;}"][vc_custom_heading text="Art Gallery" font_container="tag:div|font_size:4em|text_align:center|color:%23ffffff|line_height:1.2em" use_theme_fonts="yes" font_weight="600" text_transform="uppercase" css=".vc_custom_1525069597601{margin-bottom: 15px !important;}"][vc_column_text css=".vc_custom_1525069603112{margin-bottom: 0px !important;}"]</p>
<p style="text-align: center;">It would be great to hear from you! If you got any questions, please do not hesitate to send us a message.</p>
<p>[/vc_column_text][/vc_column_inner][/vc_row_inner][vc_icon type="entypo" icon_entypo="entypo-icon entypo-icon-down-dir" color="custom" size="xl" align="right" custom_color="#2a4670" css=".vc_custom_1526452283139{margin-bottom: 10px !important;padding-right: 4% !important;}"][contact-form-7 id="4"][/vc_column][/vc_row]</p>
CONTENT',
);
