<?php
/**
 * Form With Contact Info
 *
 * @package CiyaShop
 */

return array(
	'name'              => esc_html__( 'Form With Contact Info', 'ciyashop' ),
	'template_category' => esc_html__( 'Form', 'ciyashop' ),
	'disabled'          => true, // Disable it to not show in the default tab.
	'content'           => <<<CONTENT
[vc_row pgscore_enable_responsive_settings="true" el_id="1523882268718-905d6973-fa1f" css=".vc_custom_1524287232668{padding-top: 60px !important;padding-bottom: 100px !important;}" element_css_md=".vc_custom_1524287232672{padding-top: 60px !important;padding-bottom: 110px !important;}" element_css_sm=".vc_custom_1524287232673{padding-top: 50px !important;padding-bottom: 50px !important;}" element_css_xs=".vc_custom_1524287232675{padding-top: 40px !important;padding-bottom: 40px !important;}"][vc_column css=".vc_custom_1524285742985{margin-bottom: 0px !important;}" offset="vc_col-lg-offset-2 vc_col-lg-8 vc_col-md-offset-1 vc_col-md-10" el_id="1545213917817-1e7fbf97-aa0c"][vc_custom_heading text="Let's get in touch!" font_container="tag:h3|text_align:center" use_theme_fonts="yes"][vc_column_text css=".vc_custom_1524285534597{margin-bottom: 0px !important;}"]
<p style="text-align: center;">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's when an unknown printer took.</p>
[/vc_column_text][/vc_column][/vc_row][vc_row el_id="1523883218538-4eaae810-3b06" css=".vc_custom_1523942749389{margin-right: 0px !important;margin-left: 0px !important;}"][vc_column pgscore_enable_responsive_settings="true" css=".vc_custom_1546516632819{padding-top: 80px !important;padding-right: 150px !important;padding-bottom: 40px !important;padding-left: 50px !important;background-image: url(https://ciyashop.potenzaglobalsolutions.com/antique/wp-content/uploads/sites/16/2018/04/15.jpg?id=670) !important;}" el_class="antique-address-block" offset="vc_col-lg-6 vc_col-md-6" element_css_md=".vc_custom_1546516632822{padding-top: 40px !important;padding-bottom: 0px !important;}" element_css_sm=".vc_custom_1546516632822{padding-right: 50px !important;}" element_css_xs=".vc_custom_1546516632824{padding-right: 15px !important;padding-left: 15px !important;}"][vc_custom_heading text="Location" font_container="tag:h2|text_align:left|color:%23ffffff" use_theme_fonts="yes"][vc_column_text]
<p style="color: #ffffff">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy.</p>
[/vc_column_text][pgscore_info_box_2 icon_position="left" title_el="h6" title_color="#ffffff" description_color="#ffffff" icon_style="flat" icon_size="sm" icon_shape="round" icon_background_color="#7b5325" icon_source="font" icon_color="#ffffff" icon_fontawesome="fa fa-home" layout="style_2" title="Address" element_css=".vc_custom_1544159560740{margin-bottom: 40px !important;}" content_alignment="center" add_anchor="" anchor_link="" info_content="1635 Franklin Street Montgomery, Near Sherwood Mall. AL 36104" background_options="border" title_hover_color="#04d39f" backround_img="" element_back_color="#F5F5F5" element_hover_color="#323232" border_width="5" border_color="#F5F5F5" border_hover_color="#04d39f" add_animation="true" icon_border_color="#ccc" icon_image="" element_id="" element_class="" icon_type="fontawesome" icon_openiconic="vc-oi vc-oi-dial" icon_typicons="typcn typcn-adjust-brightness" icon_entypo="entypo-icon entypo-icon-note" icon_linecons="vc_li vc_li-heart" icon_monosocial="vc-mono vc-mono-fivehundredpx" icon_material="vc-material vc-material-cake" icon_pixelicons="vc_pixel_icon vc_pixel_icon-alert" icon_flaticon="glyph-icon flaticon-right-arrow-1"][pgscore_info_box_2 icon_position="left" title_el="h6" title_color="#ffffff" description_color="#ffffff" icon_style="flat" icon_size="sm" icon_shape="round" icon_background_color="#7b5325" icon_source="font" icon_color="#ffffff" icon_fontawesome="fa fa-phone" layout="style_2" title="Phone" element_css=".vc_custom_1544159572775{margin-bottom: 40px !important;}" content_alignment="center" add_anchor="" anchor_link="" info_content="126-632-2345<br />
857-778-1265" background_options="border" title_hover_color="#04d39f" backround_img="" element_back_color="#F5F5F5" element_hover_color="#323232" border_width="5" border_color="#F5F5F5" border_hover_color="#04d39f" add_animation="true" icon_border_color="#ccc" icon_image="" element_id="" element_class="" icon_type="fontawesome" icon_openiconic="vc-oi vc-oi-dial" icon_typicons="typcn typcn-adjust-brightness" icon_entypo="entypo-icon entypo-icon-note" icon_linecons="vc_li vc_li-heart" icon_monosocial="vc-mono vc-mono-fivehundredpx" icon_material="vc-material vc-material-cake" icon_pixelicons="vc_pixel_icon vc_pixel_icon-alert" icon_flaticon="glyph-icon flaticon-right-arrow-1"][pgscore_info_box_2 icon_position="left" title_el="h6" title_color="#ffffff" description_color="#ffffff" icon_style="flat" icon_size="sm" icon_shape="round" icon_background_color="#7b5325" icon_source="font" icon_color="#ffffff" icon_fontawesome="fa fa-envelope-o" layout="style_2" title="Email" element_css=".vc_custom_1544159582031{margin-bottom: 40px !important;}" content_alignment="center" add_anchor="" anchor_link="" info_content="support@ciyashop.com<br />
gethelp@ciyashop.com" background_options="border" title_hover_color="#04d39f" backround_img="" element_back_color="#F5F5F5" element_hover_color="#323232" border_width="5" border_color="#F5F5F5" border_hover_color="#04d39f" add_animation="true" icon_border_color="#ccc" icon_image="" element_id="" element_class="" icon_type="fontawesome" icon_openiconic="vc-oi vc-oi-dial" icon_typicons="typcn typcn-adjust-brightness" icon_entypo="entypo-icon entypo-icon-note" icon_linecons="vc_li vc_li-heart" icon_monosocial="vc-mono vc-mono-fivehundredpx" icon_material="vc-material vc-material-cake" icon_pixelicons="vc_pixel_icon vc_pixel_icon-alert" icon_flaticon="glyph-icon flaticon-right-arrow-1"][/vc_column][vc_column pgscore_enable_responsive_settings="true" css=".vc_custom_1546518176420{margin-top: -60px !important;padding-top: 0px !important;background-color: #f5f5f5 !important;}" el_class="antique-contact-form" offset="vc_col-lg-6 vc_col-md-6" element_css_sm=".vc_custom_1546518176425{margin-top: 40px !important;}"][vc_row_inner][vc_column_inner pgscore_enable_responsive_settings="true" css=".vc_custom_1546518197375{margin-left: -60px !important;padding-top: 95px !important;padding-bottom: 95px !important;padding-left: 70px !important;background-color: #f5f5f5 !important;}" element_css_sm=".vc_custom_1546518197377{margin-left: 0px !important;}"][contact-form-7 id="671"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]

CONTENT
);
