<?php
/**
 * Infobox With Image Style 2
 *
 * @package CiyaShop
 */

return array(
	'name'              => esc_html__( 'Infobox With Image Style 2', 'ciyashop' ),
	'template_category' => esc_html__( 'Info Box', 'ciyashop' ),
	'disabled'          => true, // Disable it to not show in the default tab.
	'content'           => '<<<CONTENT
	<p>[vc_row full_width="stretch_row_content_no_spaces" equal_height="yes" content_placement="middle" pgscore_bg_type="row-background-light" pgscore_enable_responsive_settings="true" el_id="1534920543931-69885343-a7c1" css=".vc_custom_1545207548352{margin-top: 80px !important;margin-bottom: 80px !important;background-color: #3d4457 !important;}" element_css_md=".vc_custom_1545207548355{margin-top: 60px !important;margin-bottom: 0px !important;}" element_css_sm=".vc_custom_1545207548358{margin-top: 50px !important;margin-bottom: 0px !important;}" element_css_xs=".vc_custom_1545207548360{margin-top: 40px !important;margin-bottom: 0px !important;}"][vc_column pgscore_enable_responsive_settings="true" css=".vc_custom_1543920518952{margin-top: 8% !important;margin-right: 17% !important;margin-bottom: 8% !important;margin-left: 17% !important;padding-top: 0px !important;}" offset="vc_col-lg-offset-1 vc_col-lg-6 vc_col-md-12" element_css_md=".vc_custom_1543920518953{margin-top: 6% !important;margin-bottom: 6% !important;}" element_css_sm=".vc_custom_1543920518954{margin-top: 5% !important;margin-bottom: 5% !important;}" element_css_xs=".vc_custom_1543920518956{margin-top: 10% !important;margin-bottom: 10% !important;}"][vc_custom_heading text="Why Choose Us?" font_container="tag:h2|text_align:left|color:%23ffffff" use_theme_fonts="yes"][vc_column_text]</p>
	<p style="color: #9ea2ab">We know this in our gut, but what can we do about it? How can we motivate ourselves? One of the most difficult aspects of achieving success is staying motivated over the long haul.</p>
	<p>[/vc_column_text][pgscore_info_box_2 icon_position="left" title_el="h6" title_color="#ffffff" icon_source="link" layout="style_2" title="100% Pure product" icon_image="482" element_css=".vc_custom_1565594168358{margin-top: 30px !important;margin-bottom: 30px !important;}" content_alignment="center" add_anchor="" anchor_link="" info_content="The first thing to remember about success is that it is a process<br />
	nothing more nothing less." description_color="#9ea2ab" background_options="border" title_hover_color="#04d39f" backround_img="" element_back_color="#F5F5F5" element_hover_color="#323232" border_width="5" border_color="#F5F5F5" border_hover_color="#04d39f" icon_style="default" icon_size="md" disable_animation="1" icon_shape="square" icon_background_color="#cccccc" icon_border_color="#cccccc" icon_color="#323232" element_id="" element_class="" icon_type="fontawesome" icon_fontawesome="fa fa-info-circle" icon_openiconic="vc-oi vc-oi-dial" icon_typicons="typcn typcn-adjust-brightness" icon_entypo="entypo-icon entypo-icon-note" icon_linecons="vc_li vc_li-heart" icon_monosocial="vc-mono vc-mono-fivehundredpx" icon_material="vc-material vc-material-cake" icon_pixelicons="vc_pixel_icon vc_pixel_icon-alert" icon_flaticon="" image_link="https://ciyashop.potenzaglobalsolutions.com/ceramic/wp-content/uploads/sites/35/2018/08/product-icon.png" icon_themefy="ti-arrow-up"][pgscore_info_box_2 icon_position="left" title_el="h6" title_color="#ffffff" icon_source="link" layout="style_2" title="Free Delivery" icon_image="481" element_css=".vc_custom_1565594180357{margin-bottom: 30px !important;}" content_alignment="center" add_anchor="" anchor_link="" info_content="Reflect and experiment until you find the right combination of motivators for<br />
	your personality and your personal goals." description_color="#9ea2ab" background_options="border" title_hover_color="#04d39f" backround_img="" element_back_color="#F5F5F5" element_hover_color="#323232" border_width="5" border_color="#F5F5F5" border_hover_color="#04d39f" icon_style="default" icon_size="md" disable_animation="1" icon_shape="square" icon_background_color="#cccccc" icon_border_color="#cccccc" icon_color="#323232" element_id="" element_class="" icon_type="fontawesome" icon_fontawesome="fa fa-info-circle" icon_openiconic="vc-oi vc-oi-dial" icon_typicons="typcn typcn-adjust-brightness" icon_entypo="entypo-icon entypo-icon-note" icon_linecons="vc_li vc_li-heart" icon_monosocial="vc-mono vc-mono-fivehundredpx" icon_material="vc-material vc-material-cake" icon_pixelicons="vc_pixel_icon vc_pixel_icon-alert" icon_flaticon="" image_link="https://ciyashop.potenzaglobalsolutions.com/ceramic/wp-content/uploads/sites/35/2018/08/delivery-icon.png" icon_themefy="ti-arrow-up"][pgscore_info_box_2 icon_position="left" title_el="h6" title_color="#ffffff" icon_source="link" layout="style_2" title="High Quality Product" icon_image="480" content_alignment="center" add_anchor="" anchor_link="" info_content="Give yourself the power of responsibility remind yourself the only<br />
	thing stopping you is yourself." description_color="#9ea2ab" background_options="border" title_hover_color="#04d39f" backround_img="" element_back_color="#F5F5F5" element_hover_color="#323232" border_width="5" border_color="#F5F5F5" border_hover_color="#04d39f" icon_style="default" icon_size="md" disable_animation="1" icon_shape="square" icon_background_color="#cccccc" icon_border_color="#cccccc" icon_color="#323232" element_css="" element_id="" element_class="" icon_type="fontawesome" icon_fontawesome="fa fa-info-circle" icon_openiconic="vc-oi vc-oi-dial" icon_typicons="typcn typcn-adjust-brightness" icon_entypo="entypo-icon entypo-icon-note" icon_linecons="vc_li vc_li-heart" icon_monosocial="vc-mono vc-mono-fivehundredpx" icon_material="vc-material vc-material-cake" icon_pixelicons="vc_pixel_icon vc_pixel_icon-alert" icon_flaticon="" image_link="https://ciyashop.potenzaglobalsolutions.com/ceramic/wp-content/uploads/sites/35/2018/08/quality-icon.png" icon_themefy="ti-arrow-up"][/vc_column][vc_column css=".vc_custom_1534922461589{padding-top: 0px !important;background-color: #ffffff !important;}" offset="vc_col-lg-5 vc_col-md-12"][vc_row_inner equal_height="yes" content_placement="middle" pgscore_enable_responsive_settings="true" css=".vc_custom_1543392803027{padding-top: 75px !important;padding-bottom: 45px !important;}" element_css_md=".vc_custom_1543392803029{padding-top: 55px !important;}" element_css_sm=".vc_custom_1543392803029{padding-top: 45px !important;}"][vc_column_inner width="1/3" pgscore_enable_responsive_settings="true" css=".vc_custom_1543921103175{margin-right: 30px !important;margin-left: -101px !important;}" offset="vc_col-lg-offset-0 vc_col-lg-4 vc_col-md-offset-1 vc_col-md-4 vc_col-sm-offset-1 vc_col-xs-5" element_css_md=".vc_custom_1543921103176{margin-left: 0px !important;}" element_css_sm=".vc_custom_1543921103178{margin-right: 25px !important;}" element_css_xs=".vc_custom_1543921103178{margin-right: 15px !important;}"][vc_single_image source="external_link" custom_src="https://ciyashop.potenzaglobalsolutions.com/ceramic/wp-content/uploads/sites/35/2018/08/info-img1.jpg"][/vc_column_inner][vc_column_inner width="1/2" offset="vc_col-lg-8 vc_col-md-6 vc_col-xs-7"][vc_single_image source="external_link" custom_src="https://ciyashop.potenzaglobalsolutions.com/ceramic/wp-content/uploads/sites/35/2018/08/info-img2.jpg"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]</p>	
CONTENT',
);
