<?php
/**
 * Video With Info
 *
 * @package CiyaShop
 */

return array(
	'name'              => esc_html__( 'Video With Info', 'ciyashop' ),
	'template_category' => esc_html__( 'Video', 'ciyashop' ),
	'disabled'          => true, // Disable it to not show in the default tab.
	'content'           => <<<CONTENT
[vc_row full_width="stretch_row" equal_height="yes" content_placement="top" pgscore_enable_responsive_settings="true" el_id="1523966087888-64cb7801-9adf" css=".vc_custom_1533541136259{padding-top: 80px !important;padding-bottom: 20px !important;}" element_css_md=".vc_custom_1533541136261{padding-top: 60px !important;padding-bottom: 30px !important;}" element_css_sm=".vc_custom_1533541136262{padding-top: 50px !important;padding-bottom: 20px !important;}" element_css_xs=".vc_custom_1533541136263{padding-top: 40px !important;padding-bottom: 10px !important;}"][vc_column css=".vc_custom_1524054906027{margin-bottom: 30px !important;padding-top: 0px !important;}" offset="vc_col-lg-6 vc_col-md-6" el_id="1545461617067-ea27c9fa-d3b4"][vc_video link="https://www.youtube.com/watch?v=g00amCRP_Uk" css=".vc_custom_1546509961456{margin-bottom: 0px !important;}"][/vc_column][vc_column css=".vc_custom_1524054915585{margin-bottom: 30px !important;padding-top: 0px !important;}" offset="vc_col-lg-6 vc_col-md-6" el_id="1545461617109-6b63a275-1d47"][vc_custom_heading text="Quality & Reliable" use_theme_fonts="yes" css=".vc_custom_1523968313758{margin-bottom: 20px !important;}"][vc_column_text css=".vc_custom_1533646156053{margin-bottom: 20px !important;}"]I truly believe Augustine's words are true and if you look at history you know it is true. There are many people in the world with amazing talents.[/vc_column_text][pgscore_info_box_2 icon_position="left" title_el="h4" description_color="#888888" icon_source="link" layout="style_2" title="100% Pure Leather" icon_image="488" content_alignment="center" add_anchor="" anchor_link="" title_color="#323232" info_content="Commitment – understanding the price<br />
and having the willingness to pay that price" background_options="border" title_hover_color="#04d39f" backround_img="" element_back_color="#F5F5F5" element_hover_color="#323232" border_width="5" border_color="#F5F5F5" border_hover_color="#04d39f" icon_style="default" icon_size="md" add_animation="true" icon_shape="square" icon_background_color="#cccccc" icon_border_color="#cccccc" icon_color="#323232" element_css="" element_id="" element_class="" icon_type="fontawesome" icon_fontawesome="fa fa-info-circle" icon_openiconic="vc-oi vc-oi-dial" icon_typicons="typcn typcn-adjust-brightness" icon_entypo="entypo-icon entypo-icon-note" icon_linecons="vc_li vc_li-heart" icon_monosocial="vc-mono vc-mono-fivehundredpx" icon_material="vc-material vc-material-cake" icon_pixelicons="vc_pixel_icon vc_pixel_icon-alert" icon_flaticon="" disable_animation="" image_link="https://ciyashop.potenzaglobalsolutions.com/leather/wp-content/uploads/sites/28/2018/08/icon-01.png" icon_themefy="ti-arrow-up"][vc_empty_space height="30px"][pgscore_info_box_2 icon_position="left" title_el="h4" description_color="#888888" icon_source="link" layout="style_2" title="Free Delivery" icon_image="489" content_alignment="center" add_anchor="" anchor_link="" title_color="#323232" info_content="If success is a process with a number<br />
of defined steps, then it is just like" background_options="border" title_hover_color="#04d39f" backround_img="" element_back_color="#F5F5F5" element_hover_color="#323232" border_width="5" border_color="#F5F5F5" border_hover_color="#04d39f" icon_style="default" icon_size="md" add_animation="true" icon_shape="square" icon_background_color="#cccccc" icon_border_color="#cccccc" icon_color="#323232" element_css="" element_id="" element_class="" icon_type="fontawesome" icon_fontawesome="fa fa-info-circle" icon_openiconic="vc-oi vc-oi-dial" icon_typicons="typcn typcn-adjust-brightness" icon_entypo="entypo-icon entypo-icon-note" icon_linecons="vc_li vc_li-heart" icon_monosocial="vc-mono vc-mono-fivehundredpx" icon_material="vc-material vc-material-cake" icon_pixelicons="vc_pixel_icon vc_pixel_icon-alert" icon_flaticon="" disable_animation="" image_link="https://ciyashop.potenzaglobalsolutions.com/leather/wp-content/uploads/sites/28/2018/08/icon-02.png" icon_themefy="ti-arrow-up"][/vc_column][/vc_row]
CONTENT
);
